Controllers/PartialController.cs
using DynamicData.Interface;
using DynamicData.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Threading.Tasks;

namespace DynamicData.Controllers
{
    public class PartialController : Controller
    {
        private readonly IUser _iUser;
        private readonly IField _iField;
        private readonly IItem _iItem;
        private readonly IFieldValue _iFieldValue;
        private readonly ILibrary _iLibrary;
        private readonly ICommon _iCommon;

        public PartialController(IUser iUser, IField iField, IFieldValue iFieldValue, ILibrary iLibrary, ICommon iCommon,IItem iItem)
        {
            _iUser = iUser;
            _iField = iField;
            _iFieldValue = iFieldValue;
            _iLibrary = iLibrary;
            _iCommon = iCommon;
            _iItem = iItem;
        }

        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        [Route("Partial/_FieldAction")]
        public async Task<IActionResult> _ActionField(string guid, Guid libraryGuid)
        {
            Guid Guid = Guid.Empty;
            if ((guid != "") && (guid != "0"))
                Guid = Guid.Parse(string.IsNullOrEmpty(guid) ? Guid.NewGuid().ToString() : guid);
            try
            {
                var calculatedField = await _iField.FindByLibraryGuid(libraryGuid);
                if (guid != "0") // load Field object with value for edit form
                {
                    var field = await _iField.FindByGuid(Guid);
                    field.IsEditable = (field.Editable == 1) ? true : false;
                    field.IsVisible = (field.Visible == 1) ? true : false;
                    field.IsRequired = (field.Required == 1) ? true : false;
                    field.IsGrouping = (field.Grouping == 1) ? true : false;
                    field.IsDefaultSort = (field.DefaultSort == 1) ? true : false;
                    field.IsCheckDuplicate = (field.CheckDubplicate == 1) ? true : false;
                    field.FormularLibraryGuid = libraryGuid;
                    field.LibraryCollection = _iCommon.LibraryHierarchy();
                    field.CalculatedField = calculatedField;
                    return View(field);
                }
                else // load empty Field Object for add form
                {
                    Field field = await _iField.EmptyFieldForView();
                    field.IsEditable = true;
                    field.IsVisible = true;
                    field.IsRequired = false;
                    field.IsGrouping = false;
                    field.IsDefaultSort = false;
                    field.IsCheckDuplicate = false;
                    field.FormularLibraryGuid = libraryGuid;
                    field.LibraryCollection = _iCommon.LibraryHierarchy();
                    field.CalculatedField = calculatedField;
                    return View(field);
                }
            }
            catch (Exception ex)
            {

            }
            return View(new Field());
        }

        [HttpPost]
        [Route("Partial/_FieldAction/{guid?}")]
        public async Task<IActionResult> _ActionField(Field field)
        {
            bool status = false;
            string message = "";
            Guid libraryGuid = Guid.Empty;
            string queryGuid = Common.GetGuidFromURL(Request.Path.ToString());
            if (!string.IsNullOrEmpty(queryGuid))
                libraryGuid = Guid.Parse(queryGuid);
            if (!await DublicateFieldName(field, libraryGuid))
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        if (field.ID == 0) // Add new field
                        {
                            field.LibraryGuid = libraryGuid;
                            field.GUID = Guid.NewGuid();
                            field.Visible = (field.IsVisible) ? 1 : 0;                         
                            field.Required = (field.IsRequired) ? 1 : 0;
                            field.Grouping = (field.IsGrouping) ? 1 : 0;
                            field.DefaultSort = (field.IsDefaultSort) ? 1 : 0;
                            field.CheckDubplicate = (field.IsCheckDuplicate) ? 1 : 0;
                            field.SortOrder = 100;
                            field.Deleted = 0;
                            if (field.FormularView == "" || field.FormularView == null)
                            {
                                field.Editable = (field.IsEditable) ? 1 : 0;
                            }
                            else
                                field.Editable = 0;

                           await _iField.Add(field);
                            status = true;
                            message = field.Title + " has been added to Library.";
                        }
                        else // update field
                        {
                            field.LibraryGuid = libraryGuid;
                            field.Visible = (field.IsVisible) ? 1 : 0;                           
                            field.Required = (field.IsRequired) ? 1 : 0;
                            field.Grouping = (field.IsGrouping) ? 1 : 0;
                            field.DefaultSort = (field.IsDefaultSort) ? 1 : 0;
                            field.CheckDubplicate = (field.IsCheckDuplicate) ? 1 : 0;
                            field.Deleted = 0;
                            if (field.FormularView == "" || field.FormularView == null)
                            {
                                field.Editable = (field.IsEditable) ? 1 : 0;
                            }
                            else
                                field.Editable = 0;
                            await _iField.Update(field);
                            status = true;
                            message = field.Title + " has been updated.";
                        }
                        // Update Calculate Field value when new Calculate Field is added
                        if (field.FormularView !="")
                        {
                            List<Item> libraryItems = await _iItem.ItemCollection(libraryGuid);
                           foreach (Item item in libraryItems)
                            {
                                if (!string.IsNullOrEmpty(field.Formular))
                                {
                                   
                                    if (field.Formular.IndexOf(field.GUID.ToString()) > -1)
                                        await _iFieldValue.CalculateFormularField(item.ID,0, field.GUID);
                                    else
                                    {
                                        string formular = field.Formular;
                                        string function = formular.Substring(1, formular.IndexOf("()") - 1);
                                        string formularRaw = formular.Substring(formular.IndexOf("()(") + 3).TrimEnd(new char[] { ')', ')' });
                                        string[] formularDef = formularRaw.Split(',');
                                        string calculatedValue = "";
                                        FieldValue targetFieldValue ;
                                        try
                                        {
                                            var calculatedFieldValue = _iFieldValue.FindbyGuidAndLibraryGuidAndItemID(Guid.Parse(formularDef[0].Replace("[", "").Replace("]", "")), libraryGuid, item.ID).Result;
                                            if (calculatedFieldValue != null)
                                                calculatedValue = calculatedFieldValue.Value;
                                            targetFieldValue = await _iFieldValue.FindbyGuidAndLibraryGuidAndItemID(field.GUID, libraryGuid, item.ID);
                                            if (targetFieldValue == null)
                                            {
                                                targetFieldValue = new FieldValue();
                                                targetFieldValue.ItemID = item.ID;
                                                targetFieldValue.LibraryGuid = libraryGuid;
                                                targetFieldValue.FieldID = field.ID;
                                                targetFieldValue.Value = "";
                                                await _iFieldValue.Add(targetFieldValue);
                                            }
                                            if (function == "Year")
                                            {
                                                targetFieldValue.Value = DateTime.Parse(calculatedValue, new CultureInfo("en-US")).Year.ToString();
                                                await _iFieldValue.Update(targetFieldValue);
                                            }
                                            else if (function == "MonthYear")
                                            {
                                                targetFieldValue.Value = DateTime.Parse(calculatedValue, new CultureInfo("en-US")).Year.ToString() + "-" + DateTime.Parse(calculatedValue, new CultureInfo("en-US")).Month.ToString();
                                                await _iFieldValue.Update(targetFieldValue);
                                            }
                                        }
                                        catch (Exception ex)
                                        {

                                        }
                                    }
                                }
                            }
                        }
                        status = true;
                    }
                }

Views/Partial/_LinkToLibrary.cshtml
@{ Layout = null; }
@model DynamicData.Models.LinkLibrary
<table id="linkLibrary" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th></th>
            <th>Field</th>
            <th>Link Library</th>
            <th>Dependent Field</th>
        </tr>
    </thead>
</table>

<div class="row">
    <div class="col-sm-4 col-form-label text-sm-right pr-0">
        <div class="col-form-label text-sm-left pr-0">
            @Html.LabelFor(x => x.SetField, new { @class = "col-form-label text-sm-right" })
        </div>
        <div>
            @Html.DropDownListFor(model => model.SetField, new SelectList(Model.Fields, "GUID", "Title"), "Select Field", new { @class = "form-control col-xs-10 col-sm-9", @placeholder = "Library Type", @Required = "required" })
            <span asp-validation-for="SetField" class="form-text d-inline-block text-danger text-75 text-600 ml-sm-2"></span>
        </div>
    </div>
    <div class="col-sm-4 col-form-label text-sm-right pr-0">
        <div class="col-form-label text-sm-left pr-0">
            @Html.LabelFor(x => x.LinkToLibrary, new { @class = "col-form-label text-sm-right" })
        </div>
        <div>
            @Html.DropDownListFor(model => model.LinkToLibrary, new SelectList(Model.LinkToLibrary, "GUID", "Title"), "Select Link Library", new { @class = "form-control col-xs-10 col-sm-9", @placeholder = "Library Type", @Required = "required", onchange = "getFieldByLookupTable(this)" })
            <span asp-validation-for="LinkToLibrary" class="form-text d-inline-block text-danger text-75 text-600 ml-sm-2"></span>
        </div>
    </div>
    <div class="col-sm-4 col-form-label text-sm-right pr-0">
        <div class="col-form-label text-sm-left pr-0">
            @Html.LabelFor(x => x.DependentFields, new { @class = "col-form-label text-sm-right" })
        </div>
        <div>
            @Html.DropDownListFor(model => model.DependentFields, new SelectList(Model.DependentFields, "GUID", "Title"), "Select Dependent Field", new { @class = "form-control col-xs-10 col-sm-9", @placeholder = "Library Type", @Required = "required" })
            <span asp-validation-for="DependentFields" class="form-text d-inline-block text-danger text-75 text-600 ml-sm-2"></span>
        </div>
    </div>

</div>
<script>

    $('#linkLibrary').DataTable({
        ajax: '@Url.Action("LoadLinkLibrary", "Partial")?libraryGuid=@Model.LibraryGuid',
        columns: [
            {
                "data": "id", render: function (data, type, row, meta) {
                    return "<button class=\"btn btn-xs btn-danger btn_removerow\" onclick=\"removeLinkLibrary('" + data + "')\"><i class=\"fa  fa-trash\"></i></button>";
                } },
            { "data": "name" },
            { "data": "linktable" },
            { "data": "lookupfield" }]
    });
</script>